[theme]
# السيم الأساسي (دارك زي واجهة Hudl)
base="dark"

# اللون البرتقالي المميز لـ Hudl (للزراير والعلامات)
primaryColor="#FF5100"

# لون الخلفية الأساسية (رمادي غامق شيك جداً)
backgroundColor="#191A1E"

# لون خلفية الجداول والقوائم (رمادي أفتح سيكا عشان يبرز الجدول)
secondaryBackgroundColor="#26292E"

# لون الكلام (أبيض عشان ينور على الخلفية الغامقة)
textColor="#FFFFFF"

# نوع الخط
font="sans serif"
